// Generated by CoffeeScript 1.6.3
(function() {
    var e, t, n;
    jQuery.fn.extend({
        exchangeClass: function(e, t) {
            this.removeClass(e).addClass(t);
            return this;
        },
        removeStyle: function() {
            this.removeAttr("style");
            return this;
        }
    });
    e = {
        go: function() {
            e.onInit();
            return e.onFullLoad();
        },
        onInit: function() {
            t.go();
            return n.go();
        },
        onFullLoad: function() {
            return $(window).bind("load", function() {});
        }
    };
    n = {
        elements: {
            link: $(".main-nav a"),
            header: $(".header")
        },
        go: function() {
            var e, t;
            e = n.elements.link;
            t = n.elements.header.height();
            return e.on("click", function(e) {
                var n;
                e.preventDefault();
                n = $(this).attr("href");
                return $("body, html").animate({
                    scrollTop: $(n).offset().top - t - 50
                }, 1e3);
            });
        }
    };
    t = {
        elements: {
            trigger: $("img[data-img]")
        },
        settings: {
            rel: "gallery",
            href: function() {
                return $(this).attr("data-img");
            },
            maxWidth: "90%"
        },
        go: function() {
            var e, n;
            e = t.elements.trigger;
            n = t.settings;
            return e.colorbox(n);
        }
    };
    e.go();
}).call(this);